# .readthedocs.yaml
# Read the Docs configuration file for memories.dev v2.0.5 - Collective Memory Infrastructure for AGI
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      # Install dependencies
      - python -m pip install --upgrade pip setuptools wheel
      - pip install -r docs/requirements.txt
      - pip install sphinx-rtd-theme==1.3.0
      - pip install sphinx==7.1.2
      - pip install -e .
      # Generate API documentation
      - sphinx-apidoc -o docs/source/api_reference memories/

# Sphinx configuration
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

# Python requirements
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Build documentation in additional formats
formats:
  - pdf
  - epub

# Don't use submodules for documentation
submodules:
  include: []
  recursive: false

# Search configuration
search:
  ranking:
    getting_started/*: 5
    user_guide/*: 4
    api_reference/*: 3
    examples/*: 4
    advanced_topics/*: 3
    contributing/*: 2 