# .readthedocs.yaml
# Read the Docs configuration file for memories.dev v2.0.5 - Collective Memory Infrastructure for AGI
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      # Install dependencies in the right order
      - python -m pip install --upgrade pip setuptools wheel
      # First uninstall any pre-installed docutils
      - pip uninstall -y docutils
      # Install docutils 0.18.1 which is compatible with sphinx and theme
      - pip install docutils==0.18.1
      # Install Sphinx and theme directly
      - pip install sphinx==7.1.2 sphinx-rtd-theme==1.3.0 sphinxcontrib-jquery>=4.1
      # Now install the rest of the requirements
      - pip install -r docs/requirements.txt
      # Create data and config directories needed
      - mkdir -p data/models data/cache data/datasets config
      - |
        cat > config/db_config.yml << 'EOL'
        # Mock database configuration for ReadTheDocs build
        databases:
          memory_store:
            host: localhost
            port: 5432
            user: mock_user
            password: mock_password
            database: memory_store
          vector_db:
            host: localhost
            port: 6333
            collection: memories
        EOL
      # Create diffusers mock module if it doesn't exist to avoid import errors
      - |
        DIFFUSERS_DIR="$(python -c 'import site; print(site.getsitepackages()[0])')/diffusers"
        if [ ! -d "$DIFFUSERS_DIR" ]; then
          mkdir -p "$DIFFUSERS_DIR/pipelines/stable_diffusion" "$DIFFUSERS_DIR/loaders"
          cat > "$DIFFUSERS_DIR/__init__.py" << 'EOL'
        """Mock diffusers package for documentation build."""
        __version__ = "0.25.0"  # Mock version
        from unittest.mock import MagicMock
        import sys
        class MockPipeline(MagicMock):
            __type_params__ = tuple()
            @classmethod
            def from_pretrained(cls, *args, **kwargs): return cls()
        sys.modules['diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion'] = MockPipeline()
        sys.modules['diffusers.loaders.single_file'] = MockPipeline()
        pipeline = MockPipeline
        StableDiffusionPipeline = MockPipeline
        EOL
        fi
      # Create any missing directories that might be referenced
      - mkdir -p docs/source/getting_started
      - |
        cat > docs/source/getting_started/index.rst << 'EOL'
        ===============
        Getting Started
        ===============

        This is a placeholder for the Getting Started guide.
        
        Installation
        -----------
        
        Configuration
        ------------
        
        Examples
        --------
        EOL
      # Install the package itself in development mode with docs extras
      - pip install -e ".[docs]" || pip install -e .
      # Generate API documentation
      - sphinx-apidoc -o docs/source/api_reference memories/ || echo "API doc generation failed"
      # Clear any cached files to ensure fresh build
      - rm -rf docs/source/_build
      # Ensure chapter_heading.html exists with simplified approach to avoid syntax errors
      - mkdir -p docs/source/_templates
      - |
        cat > docs/source/_templates/chapter_heading.html << 'EOL'
        {# Simple chapter heading template that avoids complex Jinja2 syntax #}
        {% if pagename == 'preface' %}
        <div class="chapter-heading">
            <div class="chapter-number">Preface</div>
            <div class="chapter-decoration">
                <div class="chapter-line"></div>
                <div class="chapter-ornament">❧</div>
                <div class="chapter-line"></div>
            </div>
        </div>
        {% elif pagename == 'getting_started/index' %}
        <div class="chapter-heading">
            <div class="chapter-number">Chapter 1</div>
            <div class="chapter-decoration">
                <div class="chapter-line"></div>
                <div class="chapter-ornament">❧</div>
                <div class="chapter-line"></div>
            </div>
        </div>
        {% elif pagename == 'core_concepts/index' %}
        <div class="chapter-heading">
            <div class="chapter-number">Chapter 2</div>
            <div class="chapter-decoration">
                <div class="chapter-line"></div>
                <div class="chapter-ornament">❧</div>
                <div class="chapter-line"></div>
            </div>
        </div>
        {% elif pagename == 'memory_architecture/index' %}
        <div class="chapter-heading">
            <div class="chapter-number">Chapter 3</div>
            <div class="chapter-decoration">
                <div class="chapter-line"></div>
                <div class="chapter-ornament">❧</div>
                <div class="chapter-line"></div>
            </div>
        </div>
        {% elif pagename == 'memory_types/index' %}
        <div class="chapter-heading">
            <div class="chapter-number">Chapter 4</div>
            <div class="chapter-decoration">
                <div class="chapter-line"></div>
                <div class="chapter-ornament">❧</div>
                <div class="chapter-line"></div>
            </div>
        </div>
        {% elif pagename == 'earth_memory/index' %}
        <div class="chapter-heading">
            <div class="chapter-number">Chapter 5</div>
            <div class="chapter-decoration">
                <div class="chapter-line"></div>
                <div class="chapter-ornament">❧</div>
                <div class="chapter-line"></div>
            </div>
        </div>
        {% elif pagename == 'integration/index' %}
        <div class="chapter-heading">
            <div class="chapter-number">Chapter 6</div>
            <div class="chapter-decoration">
                <div class="chapter-line"></div>
                <div class="chapter-ornament">❧</div>
                <div class="chapter-line"></div>
            </div>
        </div>
        {% elif pagename == 'applications/index' %}
        <div class="chapter-heading">
            <div class="chapter-number">Chapter 7</div>
            <div class="chapter-decoration">
                <div class="chapter-line"></div>
                <div class="chapter-ornament">❧</div>
                <div class="chapter-line"></div>
            </div>
        </div>
        {% elif pagename == 'api_reference/index' %}
        <div class="chapter-heading">
            <div class="chapter-number">Chapter 8</div>
            <div class="chapter-decoration">
                <div class="chapter-line"></div>
                <div class="chapter-ornament">❧</div>
                <div class="chapter-line"></div>
            </div>
        </div>
        {% endif %}
        EOL

# Sphinx configuration
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

# Python requirements
python:
  install:
    - method: pip
      path: .
    # Not using requirements.txt here since we handle it in pre_build
    
# Build documentation in additional formats
formats:
  - pdf
  - epub

# Don't use submodules for documentation
submodules:
  include: []
  recursive: false

# Search configuration
search:
  ranking:
    getting_started/*: 5
    user_guide/*: 4
    api_reference/*: 3
    examples/*: 4
    advanced_topics/*: 3
    contributing/*: 2 