# .readthedocs.yaml
# Read the Docs configuration file for memories.dev v2.0.2 - Collective Memory Infrastructure for AGI
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - latexmk
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-lang-english
    - texlive-xetex
    - texlive-luatex
    - texlive-pictures
    - texlive-science
    - texlive-plain-generic
    - texlive-fonts-extra
    - texlive-bibtex-extra
    - texlive-latex-base
    - texlive-font-utils
    - texlive-humanities
    - cm-super
    - dvipng
    - ghostscript
    - librsvg2-bin  # For SVG to PDF conversion
    - inkscape      # Alternative SVG converter
    - pdf2svg       # For PDF to SVG conversion if needed
    - imagemagick   # For image processing
    - fonts-liberation  # Additional fonts
    - fonts-freefont-ttf  # More fonts
  jobs:
    pre_build:
      # Core setup
      - pip install -e .
      - pip install -r docs/requirements.txt
      # Additional setup for comprehensive documentation
      - python -m pip install --upgrade pip setuptools wheel
      - python -m pip install sphinx-rtd-theme sphinx-copybutton sphinx-tabs
      # Install SVG conversion tools
      - pip install cairosvg svglib
      # Clean build directory
      - cd docs && make clean
      # Generate API documentation
      - sphinx-apidoc -o docs/source/api_reference memories/ --force --separate --module-first --no-toc
      # Create necessary directories
      - mkdir -p docs/build/latex
      - mkdir -p docs/build/pdf
      # Configure ImageMagick policy to allow PDF operations
      - sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml || true
    post_build:
      # Use our custom PDF build script instead of LaTeX
      - python fix_scripts/simple_pdf_build.py
      - mkdir -p _readthedocs/html
      - cp docs/build/pdf/memories-dev.pdf _readthedocs/html/ || echo "PDF build failed, continuing anyway"

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
  builder: html

# Documentation formats - Only include HTML
formats:
  - pdf
  - epub

# Python package installation
python:
  install:
    - requirements: docs/requirements-docs.txt
    - method: pip
      path: .
    # We don't need requirements-dev.txt since we have all PDF generation packages in docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Repository configuration
submodules:
  include: all
  recursive: true

# Search configuration
search:
  ranking:
    getting_started/*: 5
    user_guide/*: 4
    api_reference/*: 3
    examples/*: 4
    advanced_topics/*: 3
    contributing/*: 2

# Use a conda environment for additional dependencies
# conda:
#   environment: environment.yml
