# .readthedocs.yaml
# Read the Docs configuration file for memories.dev v2.0.5 - Collective Memory Infrastructure for AGI
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      # Install dependencies in the right order
      - python -m pip install --upgrade pip setuptools wheel
      # First uninstall any pre-installed docutils
      - pip uninstall -y docutils
      # Install docutils 0.18.1 which is compatible with sphinx and theme
      - pip install docutils==0.18.1
      # Install Sphinx and theme directly
      - pip install sphinx==7.1.2 sphinx-rtd-theme==1.3.0 sphinxcontrib-jquery>=4.1
      # Now install the rest of the requirements
      - pip install -r docs/requirements.txt
      # Create placeholder db_config.yml file for documentation build
      - mkdir -p config
      - |
        cat > config/db_config.yml << 'EOL'
        # Mock database configuration for ReadTheDocs build
        databases:
          memory_store:
            host: localhost
            port: 5432
            user: mock_user
            password: mock_password
            database: memory_store
          vector_db:
            host: localhost
            port: 6333
            collection: memories
        EOL
      # Create any missing directories that might be referenced
      - mkdir -p docs/source/getting_started
      - |
        cat > docs/source/getting_started/index.rst << 'EOL'
        ===============
        Getting Started
        ===============

        This is a placeholder for the Getting Started guide.
        
        Installation
        -----------
        
        Configuration
        ------------
        
        Examples
        --------
        EOL
      # Install the package itself in development mode with docs extras
      - pip install -e ".[docs]" || pip install -e .
      # Generate API documentation
      - sphinx-apidoc -o docs/source/api_reference memories/ || echo "API doc generation failed"
      # Clear any cached files to ensure fresh build
      - rm -rf docs/source/_build
      # Ensure chapter_heading.html exists
      - mkdir -p docs/source/_templates
      - |
        cat > docs/source/_templates/chapter_heading.html << 'EOL'
        {# This template adds chapter headings based on page name #}
        {% set chapters = {
          'preface': 'Preface',
          'getting_started/index': 'Chapter 1',
          'core_concepts/index': 'Chapter 2',
          'memory_architecture/index': 'Chapter 3',
          'memory_types/index': 'Chapter 4',
          'earth_memory/index': 'Chapter 5',
          'integration/index': 'Chapter 6',
          'applications/index': 'Chapter 7',
          'api_reference/index': 'Chapter 8'
        } %}
        {% if pagename in chapters %}
        <div class="chapter-heading">
            <div class="chapter-number">
                {{ chapters[pagename] }}
            </div>
            <div class="chapter-decoration">
                <div class="chapter-line"></div>
                <div class="chapter-ornament">❧</div>
                <div class="chapter-line"></div>
            </div>
        </div>
        {% endif %}
        EOL

# Sphinx configuration
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

# Python requirements
python:
  install:
    - method: pip
      path: .
    # Not using requirements.txt here since we handle it in pre_build
    
# Build documentation in additional formats
formats:
  - pdf
  - epub

# Don't use submodules for documentation
submodules:
  include: []
  recursive: false

# Search configuration
search:
  ranking:
    getting_started/*: 5
    user_guide/*: 4
    api_reference/*: 3
    examples/*: 4
    advanced_topics/*: 3
    contributing/*: 2 