# .readthedocs.yaml
# Read the Docs configuration file for memories.dev v2.0.2 - Collective Memory Infrastructure for AGI
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - latexmk
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-lang-english
    - texlive-xetex
    - texlive-luatex
    - texlive-pictures
    - texlive-science
    - texlive-plain-generic
    - texlive-fonts-extra
    - texlive-bibtex-extra
    - texlive-latex-base
    - texlive-font-utils
    - texlive-humanities
    - cm-super
    - dvipng
    - ghostscript
    - librsvg2-bin  # For SVG to PDF conversion
    - inkscape      # Alternative SVG converter
    - pdf2svg       # For PDF to SVG conversion if needed
    - imagemagick   # For image processing
    - fonts-liberation  # Additional fonts
    - fonts-freefont-ttf  # More fonts
  jobs:
    pre_build:
      # Core setup
      - pip install -e .
      - pip install -r docs/requirements.txt
      # Additional setup for comprehensive documentation
      - python -m pip install --upgrade pip setuptools wheel
      - python -m pip install sphinx-rtd-theme sphinx-copybutton sphinx-tabs
      # Install SVG conversion tools
      - pip install cairosvg svglib
      # Clean build directory
      - cd docs && make clean
      # Generate API documentation
      - sphinx-apidoc -o docs/source/api_reference memories/ --force --separate --module-first --no-toc
      # Create necessary directories
      - mkdir -p docs/build/latex
      - mkdir -p docs/build/pdf
      # Configure ImageMagick policy - try multiple possible locations
      - |
        # Try to modify existing policy files
        for policy_file in /etc/ImageMagick*/policy.xml /usr/local/etc/ImageMagick*/policy.xml; do
          if [ -f "$policy_file" ]; then
            sed -i.bak 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' "$policy_file" || true
          fi
        done
        
        # Create a custom policy file as fallback
        mkdir -p ~/.config/ImageMagick
        cat > ~/.config/ImageMagick/policy.xml << 'EOL'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE policymap [
          <!ELEMENT policymap (policy)+>
          <!ELEMENT policy EMPTY>
          <!ATTLIST policy domain (delegate|coder|filter|path|resource) #REQUIRED>
          <!ATTLIST policy name CDATA #REQUIRED>
          <!ATTLIST policy rights CDATA #IMPLIED>
          <!ATTLIST policy pattern CDATA #IMPLIED>
          <!ATTLIST policy value CDATA #IMPLIED>
        ]>
        <policymap>
          <policy domain="coder" rights="read|write" pattern="PDF" />
          <policy domain="coder" rights="read|write" pattern="LABEL" />
          <policy domain="path" rights="none" pattern="@*" />
          <policy domain="cache" name="shared-secret" value="passphrase" stealth="true" />
        </policymap>
        EOL
        
        # Set MAGICK_CONFIGURE_PATH to use our custom policy
        export MAGICK_CONFIGURE_PATH=~/.config/ImageMagick
    post_build:
      # Use our custom PDF build script instead of LaTeX
      - python fix_scripts/simple_pdf_build.py
      - mkdir -p _readthedocs/html
      - cp docs/build/pdf/memories-dev.pdf _readthedocs/html/ || echo "PDF build failed, continuing anyway"

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
  builder: html

# Documentation formats - Only include HTML
formats:
  - pdf
  - epub

# Python package installation
python:
  install:
    - requirements: docs/requirements-docs.txt
    - method: pip
      path: .
    # We don't need requirements-dev.txt since we have all PDF generation packages in docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Repository configuration
submodules:
  include: all
  recursive: true

# Search configuration
search:
  ranking:
    getting_started/*: 5
    user_guide/*: 4
    api_reference/*: 3
    examples/*: 4
    advanced_topics/*: 3
    contributing/*: 2

# Use a conda environment for additional dependencies
# conda:
#   environment: environment.yml
