# .readthedocs.yaml
# Read the Docs configuration file for memories.dev v2.0.2 - Collective Memory Infrastructure for AGI
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - latexmk
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-lang-english
    - texlive-xetex
    - texlive-luatex
    - texlive-pictures
    - texlive-science
  jobs:
    pre_build:
      # Core setup
      - pip install -e .
      - pip install -r docs/requirements.txt
      # Additional setup for comprehensive documentation
      - python -m pip install --upgrade pip setuptools wheel
      - python -m pip install sphinx-rtd-theme sphinx-copybutton sphinx-tabs
      # Generate API documentation
      - sphinx-apidoc -o docs/source/api_reference memories/

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
  builder: html

# Documentation formats
formats:
  - pdf
  - epub
  - htmlzip

# Python package installation
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
        - examples
        - dev

# Repository configuration
submodules:
  include: all
  recursive: true

# Search configuration
search:
  ranking:
    getting_started/*: 5
    user_guide/*: 4
    api_reference/*: 3
    examples/*: 4
    advanced_topics/*: 3
    contributing/*: 2
