database:
  path: "./data/db"
  name: "water_bodies.db"

data:
  raw_path: "./data/raw"
  processed_path: "./data/processed"
  overture_path: "./data/overture"
  satellite_path: "./data/satellite"
  location_data_path: "./data/location_data"

memory:
  hot_size: 50
  warm_size: 200
  cold_size: 1000

redis:
  url: "redis://localhost:6379"
  db: 0 