version: '1.0'

# GCP Standalone Deployment Configuration
deployment_type: standalone
provider: gcp

# Infrastructure Configuration
infrastructure:
  instance_type: n2-standard-8
  machine_type: n2-standard-8
  vm_size: n2-standard-8
  ami_id: null
  image:
    project: deeplearning-platform-release
    family: common-cu110
    name: latest
  region: us-central1
  availability_zones: ["us-central1-a", "us-central1-b", "us-central1-c"]
  zones: ["us-central1-a", "us-central1-b", "us-central1-c"]
  subnet_type: private
  availability: "regional"
  
  high_availability:
    enabled: true
    multi_zone: true
    instances: 3

# Operating System Configuration
os:
  type: ubuntu
  version: "20.04"
  updates:
    automatic: true
    security_only: true
  
  hardening:
    enabled: true
    profile: cis-level-1
    
  packages:
    required:
      - nvidia-driver-535
      - cuda-toolkit-12-2
      - docker-ce
      - stackdriver-agent
      - google-cloud-sdk

# Memory Management
memory:
  configuration:
    total_capacity: 1.2TB
    numa_nodes: 8
    memory_per_node: 150GB
    
    optimization:
      huge_pages: enabled
      transparent_huge_pages: "always"
      numa_balancing: enabled
      kernel_same_page_merging: enabled
    
    limits:
      application: "85%"
      system: "15%"
      swap: disabled

# GPU Configuration
gpu:
  type: nvidia_a100
  count: 8
  memory_per_gpu: 80GB
  
  cuda:
    version: "12.2"
    compute_mode: "Default"
    mig:
      enabled: true
      profiles:
        - "1g.10gb"
        - "2g.20gb"
        - "3g.40gb"
    
    optimization:
      power_limit: 400
      gpu_clock_max: 1410
      memory_clock_max: 1593
      auto_boost: enabled

# Storage Configuration
storage:
  boot_disk:
    type: pd-ssd
    size_gb: 256
    auto_delete: true
    
  data_disks:
    - name: nvme_cache
      type: pd-ssd
      size_gb: 1024
      interface: NVME
      auto_delete: false
      
    - name: persistent_data
      type: pd-ssd
      size_gb: 2048
      interface: NVME
      auto_delete: false

# Networking
networking:
  vpc:
    network: standalone-vpc
    subnet: standalone-subnet
    ip_range: "10.0.0.0/16"
  
  firewall:
    rules:
      - name: allow-internal
        allowed:
          - protocol: all
        source_ranges: ["10.0.0.0/16"]
      
      - name: allow-health-checks
        allowed:
          - protocol: tcp
            ports: ["80", "443"]
        source_ranges: ["35.191.0.0/16", "130.211.0.0/22"]

# Monitoring
monitoring:
  enabled: true
  metrics:
    - name: "CPUUtilization"
      period: 300
      threshold:
        warning: 80
        critical: 90
    - name: "MemoryUtilization"
      period: 300
      threshold:
        warning: 80
        critical: 90
  cloud_monitoring:
    enabled: true
    metrics:
      collection_interval: 30s
      retention_days: 90
  azure_monitor:
    enabled: false
  prometheus:
    node_exporter:
      enabled: true
      collectors:
        - cpu
        - diskstats
        - filesystem
        - loadavg
        - meminfo
        - netdev
        - netstat

# Security
security:
  service_account:
    email: "${SERVICE_ACCOUNT_EMAIL}"
    scopes:
      - compute-rw
      - storage-rw
      - logging-write
      - monitoring-write
    
  shielded_instance:
    enabled: true
    secure_boot: true
    vtpm: true
    integrity_monitoring: true
    
  confidential_computing:
    enabled: true
    platform: "AMD SEV"
  identity:
    type: service_account
    service_account: true
  network:
    enabled: true
    vpc: true
    firewall: true
  network_acls:
    enabled: true
    default_action: deny
    rules:
      - "10.0.0.0/16"
  compliance:
    enabled: true
    standards:
      - SOC2
      - PCI_DSS
      - HIPAA
  encryption:
    at_rest: true
    in_transit: true
    kms: true
  iam:
    enabled: true
    mfa: true
    roles:
      - name: compute.admin
        scope: project
  patching:
    enabled: true
    schedule: "0 0 * * 0"
    reboot: automatic
  ssh:
    allowed_ips: "${ALLOWED_IPS}"
    key_pair: "${KEY_PAIR_NAME}"

# Performance Optimization
performance:
  compute:
    cpu_governor: performance
    numa_policy: strict
    
  memory:
    numa_balancing: enabled
    transparent_hugepages: always
    
  storage:
    io_scheduler: none
    read_ahead_kb: 2048
    
  network:
    tcp_bbr: enabled
    jumbo_frames: enabled

# Resource Management
resource_management:
  quotas:
    cpu: 96
    memory: 1200GB
    gpu: 8
    
  limits:
    docker:
      cpu: "0-95"
      memory: "1100GB"
      gpu: "all"
    
    system:
      cpu: "0-7"
      memory: "100GB"

# Backup and Recovery
backup:
  enabled: true
  retention_days: 30
  schedule: "0 0 * * *"
  type: snapshot
  disk_snapshots:
    enabled: true
    frequency: Daily
    retention:
      daily: 7
      weekly: 4
      monthly: 12
  azure_backup:
    enabled: false
  application_data:
    enabled: true
    type: gcs
    bucket: "${BACKUP_BUCKET}"
    frequency: "0 0 * * *"
    retention_days: 30

# Maintenance
maintenance:
  updates:
    schedule: "0 0 * * 0"  # Weekly at midnight on Sunday
    max_duration: 2h
    auto_reboot: true
    
  health_checks:
    enabled: true
    interval: 5m
    timeout: 30s
    
  monitoring:
    logs:
      retention: 30d
      categories:
        - system
        - application
        - security 