name: memories-dev-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=23.3.1
  - setuptools>=69.0.2
  - wheel>=0.41.3
  - sphinx>=7.1.0
  - sphinx-rtd-theme>=1.3.0
  - pandoc>=2.3
  - graphviz>=8.1.0
  - imagemagick>=7.1.1
  - make>=4.3
  - latexmk>=4.77
  - texlive-core>=2022
  - pip:
    - -r requirements-docs.txt
    - -r build-requirements.txt
    - sphinx-autodoc-typehints>=1.25.2
    - sphinx-copybutton>=0.5.2
    - sphinx-design>=0.5.0
    - sphinx-favicon>=1.0.1
    - sphinx-inline-tabs>=2023.4.21
    - sphinx-last-updated-by-git>=0.3.6
    - sphinx-math-dollar>=1.2.1
    - sphinx-notfound-page>=1.0.0
    - sphinx-remove-toctrees>=0.0.3
    - sphinx-sitemap>=2.5.1
    - sphinx-tabs>=3.4.1
    - sphinx-togglebutton>=0.3.2
    - sphinxcontrib-mermaid>=0.9.2
    - sphinxext-opengraph>=0.8.2
    - rst2pdf>=0.100
    - reportlab>=4.0.7
    - svglib>=1.5.1
    - myst-parser>=2.0.0
    - nbsphinx>=0.9.3
    - docutils>=0.20.1
    - recommonmark>=0.7.1
    - pygments>=2.17.2
    - pillow>=10.1.0
    - m2r2>=0.3.3.post2
    - cairosvg>=2.7.0
    - watchdog>=3.0.0
    - livereload>=2.6.3
    - sphinx-autobuild>=2021.3.14
    - doc8>=1.1.1
    - rstcheck>=6.2.0
    - sphinx-lint>=0.6.7 