name: Documentation Build Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - 'setup.py'
      - 'pyproject.toml'
      - '.github/workflows/docs-test.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - 'setup.py'
      - 'pyproject.toml'
      - '.github/workflows/docs-test.yml'

jobs:
  test-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        # Install docs dependencies explicitly
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints nbsphinx sphinx-copybutton myst-parser
        pip install sphinx-design sphinxcontrib-mermaid sphinx-tabs sphinx-togglebutton sphinx-favicon sphinx-sitemap sphinx-last-updated-by-git
        # Install the package with docs extras
        pip install -e ".[docs]"
    - name: Test documentation build
      run: |
        pytest tests/test_docs.py -v 